import type { Metadata } from "next";
import { Open_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "coach.bloss.app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", openSans.className, "dark")}
    >
      <body className="min-h-full flex flex-col bg-black">{children}</body>
    </html>
  );
}
